### ISSUE TITLE
Include Python 3.0.x, 3.1.x, 3.2.x, 3.3.x, and 3.4.x

### ISSUE THREAD

**Issue by AraHaan** [adang1345/PythonWindows#1]
I cannot get the tools/msi/msi.py file to work on this versions oof.

**Comment by isc-adang** [comment]
I gave the `tools/msi/msi.py` a try, too, and I was not able to get it to work either. There must be some undocumented requirement for the build environment.

**Comment by adang1345** [comment]
I gave the `tools/msi/msi.py` file a try, too, and I was not able to get it to work. There must be some undocumented requirement for the build environment.

**Comment by adang1345** [comment]
I tried a few more times to build a Python 3.4 installer, but setting up the proper build environment is turning out to be too difficult. Requirements are not documented well. I've managed to figure out a few of the requirements from the error messages, but I've hit a dead end where it's unclear how to proceed.

**Comment by Vangelis66** [comment]
> I tried a few more times to **build a Python 3.4 installer**

FWIW, someone else successfully managed to build an **MSI** setup (32-bit) for `CPython 3.4.10`, EoS `py3.4` version (and EoS of `py3.x` on Windows XP); here it is: 

http://matejhorvat.si/en/windows/python/index.htm
