### ISSUE TITLE
Can't update python 3.9.13 to 3.9.14

### ISSUE THREAD

**Issue by fuchanghao** [adang1345/PythonWindows#10]
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32

The installer doesn't show upgrade setting.

only new install.

PS: v3.9.13 install to C:\Program Files\Python39

**Comment by adang1345** [comment]
I figured out what is causing this - I filed a bug report at https://github.com/python/cpython/issues/96729. In the meantime, I will rebuild the Python 3.9.14 installer so that is doesn't have this problem.

**Comment by adang1345** [comment]
I have updated a fixed installer for Python 3.9.14.
