### ISSUE TITLE
Can you publish your changes to the build scripts?

### ISSUE THREAD

**Issue by voltagex** [adang1345/PythonWindows#12]
Thanks for your work here, however I'd prefer to build from source myself - it's a bit strange downloading binaries from the repo itself. Could you publish your changes to the build scripts?

**Comment by adang1345** [comment]
The root of the repository contains some `.patch` files that specify what changes to the source were made. `Notes.txt` contains my notes for which `.patch` files were applied for each Python version and anything particular about the build environment that I needed in order to build that version.

**Comment by voltagex** [comment]
Whoops! Thanks.
