### ISSUE TITLE
Input using the numeric keypad does not work.

### ISSUE THREAD

**Issue by Arkads-PL** [adang1345/PythonWindows#15]
Input using the numeric keypad does not work in build 221 for Python 2.7 (ArcMap).

**Comment by adang1345** [comment]
Did you open this issue in the wrong repository? This repository does not contain installers for Python 2.7, and I am not sure what you mean by "build 221" or "ArcMap".

**Comment by Arkads-PL** [comment]
No. It's a good repository. It is a bug concerning PythonWin build 221. For different versions of Python, there is a corresponding PythonWin version. isn't it? So for Python 2.7, there is PythonWin build 221. And why Python 2.7? Because it is used in ArcMap. That's all.

**Comment by Arkads-PL** [comment]
Of course, it is. This is the same software as published https://sourceforge.net/projects/pywin32/files/pywin32/, but the latest versions are here. This is the same. 

This project is a continuation of the previous one and is exactly the same. Of course, it has something to do with Python 2.7 which is used in ArcMap. ArcMap has nothing to do with it, it's just for your information. I'm using this version PythonWin because I use ArcMap and Python 2.7. That's all. So version PythonWin build 221 has a bug - the numeric keypad does not work.

**Comment by adang1345** [comment]
The link you pointed to is a Python extension package for Windows. This repository is about building newer versions of Python itself. They are different things. This repository does not have a "build 221". I think you're intending to file your bug at https://github.com/mhammond/pywin32.

**Comment by Arkads-PL** [comment]
Really? Oh, I see. Sorry for my mistake. I don't know why I posted this here.
