### ISSUE TITLE
Unable to upgrade from 3.6.8 to 3.6.15 using your installer

### ISSUE THREAD

**Issue by SamuelMarks** [adang1345/PythonWindows#16]
![image](https://github.com/adang1345/PythonWindows/assets/807580/c32a8753-4b11-4508-acde-a001e9b05b50)

(on Windows 11)

**Comment by adang1345** [comment]
I just tried upgrading from Python 3.6.8 64-bit to 3.6.15 64-bit on Windows 11 and had no trouble. I think file permission restrictions are preventing you from upgrading. Try running the installer as an administrator if you're not already doing that, or check the permissions of the `C:\usr\Python\Python36` directory.

**Comment by SamuelMarks** [comment]
That didn't work but uninstalling and installing yours did
