### ISSUE TITLE
We can not install python-3.8.18-amd64-full.exe

### ISSUE THREAD

**Issue by kakusyouu** [adang1345/PythonWindows#18]
Hello Mr. Adang

This is Guo from Japan.
Thanks for you created this project so we can install latest version of  Python 3.8.
This is a issure  of below install.
https://github.com/adang1345/PythonWindows/blob/master/3.8.18/python-3.8.18-amd64-full.exe
After we download it from above URL, it is a 123 kb file only, so we can't finished the install.
would you check it's status.
I also check other version such like below,but same issue happen.
https://github.com/adang1345/PythonWindows/tree/master/3.8.17

Please confirm,  thanks a lot .
                                                                         Guo

**Comment by adang1345** [comment]
I think you were having a network issue. I just tried downloading the installers from the two links you posted, and the downloads are each over 40 MB.
