### ISSUE TITLE
Can you tell me how to build one installer file?

### ISSUE THREAD

**Issue by MMA92** [adang1345/PythonWindows#4]
Hey I am able to build the Installer with the scripts in Tools/msi/ but my installer consists of mutiple files (e.g. python-3.8.12.7652-amd64.exe, pip.msi, pip.wixpdb, lib.msi, lib.wixpdb and so on) ,  you mangaged to build one big file containing everything e.g. "64-bit executable installer". How do I have to change the scripts to be able to do that.

**Comment by adang1345** [comment]
Building a single-file installer can be done with the `buildrelease.bat` script. First, add the folder containing `gendef.exe` to `PATH`. (This should be `externals\windows-installer\binutils` relative to the source root.) Then, from the `Tools\msi` folder, run `buildrelease.bat -x86` to build the 32-bit installer or `buildrelease.bat -x64 --skip-pgo` to build the 64-bit installer.

**Comment by MMA92** [comment]
Thanks you very much that fixed my problem.
