### ISSUE TITLE
how to build the windows installer?

### ISSUE THREAD

**Issue by liudonghua123** [adang1345/PythonWindows#7]
Hi, I read the docs on https://cpython-core-tutorial.readthedocs.io/en/latest/build_cpython_windows.html and it seems do not provide the instructions or guides on how to make the windows installer?

I use `\Tools\msi\build.bat -x86` or `Tools\msi\buildrelease.bat -x86` currently, it only build the executables and a lot of msi.

And the build files `python-3.10.5.exe` or `python-3.10.5-amd64.exe` is quite samll.

![3f188f302fa733c53a977f9da7973fc](https://user-images.githubusercontent.com/2276718/180633619-0940c29e-f7f8-4645-84ce-35dbecb51006.jpg)

Could you share your solutions?

**Comment by adang1345** [comment]
The `buildrelease.bat` script does build the single-file Windows installer. See whether #4 helps.

**Comment by liudonghua123** [comment]
Thanks, `Tools\msi\buildrelease.bat -x86` / `Tools\msi\buildrelease.bat -x64` works for me now. It seems that it is not necessary to add the folder containing gendef.exe (This should be externals\windows-installer\binutils relative to the source root) to PATH.
