### ISSUE TITLE
Windows 7 / 8-friendly Python 3.9, 3.10 Windows installers

### ISSUE THREAD

**Issue by HackintoshHD** [adang1345/PythonWindows#8]
Starting from Python 3.9.0, [Python 3 no longer supports Windows 7 and 8](https://docs.python.org/3/using/windows.html#:%7E:text=As%20specified%20in%20PEP%2011,support%2C%20please%20install%20Python%203.8.) and the official Python 3 Windows installer refuses to install, once it detects Windows 7 or 8. 

According to @nalexandru, it is however possible to run Python 3.9 and 3.10 on Windows 7 and 8 by using his and @kobilutil 's [implementation of api-ms-win-core-path-l1-1-0.dll](https://github.com/nalexandru/api-ms-win-core-path-HACK), which itself is based on the WINE project's code. While this would be a really simple and straightforward method to make Python 3.9+ run on Windows 7 again, it is currently defeated by the official Python Windows installer's somewhat vexatious implementation of its OS check, which doesn't allow to override its decision to cancel the installation under any cirumstances (not even by an undocumented command line switch).

Hence my question: Could you also build a current 3.10.6 Windows installer for x64 and x86 with the OS check being removed? As far as I can see, modifying `tools/msi/bundle/bootstrap/PythonBootstrapperApplication.cpp` as follows should be enough:

![Python-3 10 6-Installer-Patch](https://user-images.githubusercontent.com/2894628/188271688-2052cf0e-0b8d-41ca-8cc9-02bc368ce709.png)

Thank you very much!

**Comment by iamtherobin** [comment]
Would be interested in this if it is possible.

**Comment by adang1345** [comment]
Getting the Python installers to support Windows 7 was not quite as straightforward as I initially thought, but I managed to build them successfully. The installers are at https://github.com/adang1345/PythonWin7. They not only have the OS check removed but also automatically provide `api-ms-win-core-path-l1-1-0.dll`.

**Comment by iamtherobin** [comment]
Just wanted to say thanks. I am confirm 3.10.6 installer worked on my Windows 7 x64 machine and I managed to update my Deluge client to latest version now thanks to this.

**Comment by HackintoshHD** [comment]
Wow, that was fast. Thank you very much, your work is highly appreciated!

I can confirm both installers x64 and x86 are working fine on my Windows 7 SP1 x64 test machine and I think the integration of `api-ms-win-core-path-l1-1-0.dll` into the installers is quite an elegant solution.
