### ISSUE TITLE
Sep 6th 2022 source-only releases...

### ISSUE THREAD

**Issue by Vangelis66** [adang1345/PythonWindows#9]
Hello 😄 ; many huge thanks for what you're doing (and providing) here! 👍 

**2022-09-06** saw the releases of the following **source-only**, "security bugfix release", Python editions by the **PSF**: 

[py3.7.14](https://www.python.org/downloads/release/python-3714/) (VistaSP2+)
[py3.8.14](https://www.python.org/downloads/release/python-3814/) (Win7SP1+)
and 
[py3.9.14](https://www.python.org/downloads/release/python-3914/) (Win8.1+)
(the **first** source-only release in the `3.9.x` branch...)

A repo update to accommodate these latest releases would be immensely appreciated! 😃 
Thanks in advance, take good care...

**Comment by adang1345** [comment]
Done

**Comment by Vangelis66** [comment]
Hugely indebted for your most prompt response and accompanying offerings! 🥇
